// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ecglkzeyhmmlzzmmhwxk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVjZ2xremV5aG1tbHp6bW1od3hrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3MjU1NjUsImV4cCI6MjA2NjMwMTU2NX0.MGvTpxYtvVdmXqE7iarzPgscytgz4T8AjcIw0j3-94c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);